version: '3.1'
services:
  postgresql:
    image: postgres:latest
    container_name: alpha-postgresql
    restart: always
    environment:
        POSTGRES_USER: "alpha"
        POSTGRES_PASSWORD: "alpha-password"
        POSTGRES_DB: "postgres"
    ports:
      - 8001:5432
    volumes:
      - postgresql_data:/var/lib/postgresql
 
volumes:
  postgresql_data: