version: '3.1'
services:
  manoj-mysql:
    image: mysql:latest
    container_name: manoj-mysql
    restart: always
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_ROOT_PASSWORD: "root-password"
      MYSQL_DATABASE: "mysql"
      MYSQL_USER: "manoj"
      MYSQL_PASSWORD: "manoj-password"
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: