# Generated by Django 5.0.4 on 2024-04-12 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_room_options_room_participants"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-updated", "-created"]},
        ),
    ]
